version: '3'

services:
  db:
    image: proffapt/scmb-db
    container_name: scmb-db
    environment:
      - POSTGRES_PASSWORD=postgres-scmb-db
      - POSTGRES_DB=scmb
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
